apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oc-provider-ingress
  namespace: oc-provider
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - provider.on-track.ch
      secretName: provider-on-track-ch-tls
  rules:
    - host: provider.on-track.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oc-provider-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: oc-provider-backend
                port:
                  number: 80
