name: Backend CI/CD

on:
  push:
    branches: ['main', 'dev']
  workflow_dispatch:

jobs:
  build:
    uses: julienreichel/oc-infra/.github/workflows/reusable-build.yml@main
    with:
      image_name: ghcr.io/julienreichel/oc-provider-backend
    secrets: inherit

  deploy-prod:
    if: github.ref_name == 'main'
    uses: julienreichel/oc-infra/.github/workflows/reusable-deploy.yml@main
    with:
      app_kind: backend
      image_name: ghcr.io/julienreichel/oc-provider-backend
      namespace: oc-provider
    secrets: inherit

  deploy-dev:
    if: github.ref_name == 'dev'
    uses: julienreichel/oc-infra/.github/workflows/reusable-deploy.yml@main
    with:
      app_kind: backend
      image_name: ghcr.io/julienreichel/oc-provider-backend
      namespace: oc-dev-provider
    secrets: inherit
